In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
base_credit = pd.read_csv('./credit_risk_dataset.csv')

In [3]:
base_credit

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
1            EDUCATION          B       1000          11.14            0   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
...                ...        ...        ...            ...          ...   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
0                               3  
1                               2  
2                               3  
3                               2  
4                               4  
...                           ...  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30  

[32581 rows x 12 columns]

In [2]:
X_credit = base_credit.iloc[:, [0,1,6]]
Y_credit = base_credit.iloc[:, 8]
np_x_credit = X_credit.values
np_y_credit = Y_credit.values

In [8]:
X_credit

person_age  person_income  person_emp_length loan_grade  loan_amnt
0              22          59000              123.0          D      35000
1              21           9600                5.0          B       1000
2              25           9600                1.0          C       5500
3              23          65500                4.0          C      35000
4              24          54400                8.0          C      35000
...           ...            ...                ...        ...        ...
32576          57          53000                1.0          C       5800
32577          54         120000                4.0          A      17625
32578          65          76000                3.0          B      35000
32579          56         150000                5.0          B      15000
32580          66          42000                2.0          B       6475

[32581 rows x 5 columns]

In [9]:
np_x_credit

array([[22, 59000, 123.0, 'D', 35000],
       [21, 9600, 5.0, 'B', 1000],
       [25, 9600, 1.0, 'C', 5500],
       ...,
       [65, 76000, 3.0, 'B', 35000],
       [56, 150000, 5.0, 'B', 15000],
       [66, 42000, 2.0, 'B', 6475]], dtype=object)

In [13]:
np_y_credit

array([1, 0, 1, ..., 1, 0, 0])

In [19]:
### ESCALONAMENTO DOS VALORES
### valores maiores tem peso maior, devemos escalonar para não 'enganar' o algoritimo

### a padronização (desvio padrão) é mais utilizada com outliers e a normalização (min/max)
min_age = np_x_credit[:, 0].min()
min_income = np_x_credit[:, 1].min()
#min_emp_len = np_x_credit[:, 2].min()
#min_grade = np_x_credit[:, 3].min()
min_loan = np_x_credit[:, 4].min()

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
creditStandardScaler = StandardScaler()
np_x_credit_fit = creditStandardScaler.fit_transform(np_x_credit)

In [5]:
np_x_credit_fit[:, 2]

array([ 4.01940376, -1.35864998, -0.64684875, ...,  4.01940376,
        0.85584274, -0.49262515])

In [6]:
### TREINAMENTO

from sklearn.model_selection import train_test_split

npx_train, npx_test, npy_train, npy_test = train_test_split(np_x_credit_fit, np_y_credit, test_size = 0.1, random_state = 0)

npx_train.shape, npx_test.shape, npy_train.shape, npy_test.shape

((29322, 3), (3259, 3), (29322,), (3259,))

In [ ]:
#import pickle 
#salvar variaveis no disco


In [9]:
from sklearn.naive_bayes import GaussianNB
naive_credit = GaussianNB()
naive_credit.fit(npx_train, npy_train) 

GaussianNB()

In [13]:
predict = naive_credit.predict(npx_test)
predict, npy_test

(array([0, 1, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]))

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(npy_test, predict)

0.7934949370972691

In [18]:
confusion_matrix(npy_test, predict)

array([[2520,   57],
       [ 616,   66]])

In [23]:
print(classification_report(npy_test, predict))

              precision    recall  f1-score   support

           0       0.80      0.98      0.88      2577
           1       0.54      0.10      0.16       682

    accuracy                           0.79      3259
   macro avg       0.67      0.54      0.52      3259
weighted avg       0.75      0.79      0.73      3259

